networks:
  my-network:

services:

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d userdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5440:5432"
    networks:
      - my-network

  company-db:
    image: postgres:15
    container_name: company-db
    environment:
      POSTGRES_USER: company
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: companydb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U company -d companydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5441:5432"
    networks:
      - my-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      user-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  company-service:
    build: ./company-service
    container_name: company-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://company-db:5432/companydb
      SPRING_DATASOURCE_USERNAME: company
      SPRING_DATASOURCE_PASSWORD: pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      company-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

